name: airbyte_ab_id_column_values_to_be_unique_n_qa_5
displayName: airbyte_ab_id_column_values_to_be_unique_n_qa_5
fullyQualifiedName: testUnity.postgres_catalog.sdoh_cms_dual_eligible_enrollment._airbyte_raw__airbyte_raw_new_cities._airbyte_ab_id.airbyte_ab_id_column_values_to_be_unique_n_qa_5
testDefinition:
  id: b30cf693-3fe3-4407-8964-48fb24e6e8b3
  type: testDefinition
  name: columnValuesToBeUnique
  fullyQualifiedName: columnValuesToBeUnique
  description: 'This schema defines the test ColumnValuesToBeUnique. Test the values
    in a column to be unique. '
  displayName: Column Values To Be Unique
  deleted: false
entityLink: <#E::table::testUnity.postgres_catalog.sdoh_cms_dual_eligible_enrollment._airbyte_raw__airbyte_raw_new_cities::columns::_airbyte_ab_id>
entityFQN: testUnity.postgres_catalog.sdoh_cms_dual_eligible_enrollment._airbyte_raw__airbyte_raw_new_cities._airbyte_ab_id
testSuite:
  id: 51d9a913-1f3f-426b-b416-d8d3f6cf9341
  type: testSuite
  name: testUnity.postgres_catalog.sdoh_cms_dual_eligible_enrollment._airbyte_raw__airbyte_raw_new_cities.testSuite
  fullyQualifiedName: testUnity.postgres_catalog.sdoh_cms_dual_eligible_enrollment._airbyte_raw__airbyte_raw_new_cities.testSuite
  displayName: testUnity.postgres_catalog.sdoh_cms_dual_eligible_enrollment._airbyte_raw__airbyte_raw_new_cities.testSuite
  deleted: false
testSuites:
  - id: 51d9a913-1f3f-426b-b416-d8d3f6cf9341
    name: testUnity.postgres_catalog.sdoh_cms_dual_eligible_enrollment._airbyte_raw__airbyte_raw_new_cities.testSuite
    fullyQualifiedName: testUnity.postgres_catalog.sdoh_cms_dual_eligible_enrollment._airbyte_raw__airbyte_raw_new_cities.testSuite
    serviceType: TestSuite
    owners: []
    version: 0.1
    updatedAt: 1770631532778
    updatedBy: ingestion-bot
    deleted: false
    basic: true
    basicEntityReference:
      id: 1a42483f-0d5e-4c42-b2ee-5ea1d9625643
      type: table
      name: _airbyte_raw__airbyte_raw_new_cities
      fullyQualifiedName: testUnity.postgres_catalog.sdoh_cms_dual_eligible_enrollment._airbyte_raw__airbyte_raw_new_cities
    testCaseResultSummary: []
    domains: []
    tags: []
    inherited: true
    reviewers: []
parameterValues: []
owners: []
createdBy: aniket
computePassedFailedRowCount: false
domains: []
useDynamicAssertion: false
tags: []
dimensionColumns: []
entityStatus: Unprocessed
reviewers: []
